### ISSUE TITLE
Ionic Beta 7 Bug - Argument of type 'Http' is not assignable to parameter of type 'Http'

### ISSUE THREAD

**Issue by saiy2k** [ocombe/ng2-translate#132]
With the recent Ionic update to Beta 7, I am getting this error in Terminal on `ionic serve`:

    TypeScript error: app/app.ts(27,79): Error TS2345: Argument of type 'Http' is not assignable to parameter of type 'Http'.
      Property '_backend' is protected but type 'Http' is not a class derived from 'Http'.

    useFactory          :   (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),

In above line, error is thrown at the first http parameter passed to TranslateStaticLoader

**Comment by wulfsolter** [comment]
Ionic is now at 2.0.0-beta.25, could be a good time to get up to date.

**Comment by trentclowater** [comment]
Beta 7 is the latest release of the Ionic framework (released just a few days ago). It's the Ionic CLI that is currently at 2.0.0-beta.25.

**Comment by wulfsolter** [comment]
@trentclowater Apologies, you a correct :) too many versions to keep track of, and this weeks upgrade has too often been referred to by Angular's RC1 milestone.

**Comment by katan** [comment]
The same problem here for  2.0.0-beta.6

**Comment by danielbertini** [comment]
The same problem here for beta7.

**Comment by forriteshbhat** [comment]
Same problem here for beta 7.

**Comment by saiy2k** [comment]
Upgrading to ng2-translate@2.1.0, fixed this issue :-)

Ref: https://forum.ionicframework.com/t/ocombe-ng2-translate-bug-in-ionic-beta-7-argument-of-type-http-is-not-assignable-to-parameter-of-type-http-132/53023

**Comment by Dok11** [comment]
I have same trouble with last version of ngx-translate `^7.0.0` and Angular 4.3.6

```
Failed to compile.

/data/main/src/app/app.module.ts (116,33): Argument of type 'HttpClient' is not assignable to parameter of type 'Http'.
  Property '_backend' is missing in type 'HttpClient'.
```

My code:
```ts
export function createTranslateLoader(http: HttpClient) {
	return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule({
	...
  	imports: [
		...
		FormsModule,
		TranslateModule.forRoot({
			loader: {
				provide: TranslateLoader,
				useFactory: (createTranslateLoader),
				deps: [HttpClient],
			}
		}),
	],
```

![image](https://user-images.githubusercontent.com/2697890/29781773-f6b1699c-8c22-11e7-8f67-659d59f8fdcc.png)

**Comment by rikoroku** [comment]
To: Dok11

I have the same trouble as you have.
I fixed that.

Change `package.json` :

from

```
"@ngx-translate/core": "^9.0.1",
```

to

```
"@ngx-translate/core": "^8.0.0",
```

After, deleted node_modules directory and executed `npm install`

**Comment by polfdz** [comment]
@Dok11 I have the same problem, I tried @rikoroku solution but not solved...
any update?

**Comment by Dok11** [comment]
Yes, latest version is ok
